### ISSUE TITLE
Valheim Patch 0.216.9 Integration Testing

### ISSUE THREAD

**Issue by ValhallaCommunity** [The-Bees-Decree-Server/Distant-Dynasties#4]
Hey Bees Decree Team!

`[Error  : Unity Log] MissingFieldException: Field 'ZNetScene.m_instance' not found.
Stack trace:
(wrapper dynamic-method) ItemManager.Item.DMD<ItemManager.Item::Patch_ZNetSceneAwake>(ZNetScene)
(wrapper dynamic-method) ZNetScene.DMD<ZNetScene::Awake>(ZNetScene)`

When loading up under the updated Valheim Patch, I started to remove mods 1 at a time until I no longer got this error. I removed Distance Dynasties and it resolved this error.

**Likelihood:** Very High - 100% repro rate
**Severity:** Blocker / Critical - unable to start world with this error - which shuts down the mod pack and community world.

Thanks for any expedited look into this!

**Comment by chrisjenda** [comment]
I have resolved this issue by changing Line #10 of the AssignDropToCreature Method within the ItemManager.Item Class to resolve the newly changed ZNetScene Instance which is now named s_instance instead of m_instance.
here is the changed Line
`	foreach (KeyValuePair<Character, CharacterDrop.Drop> keyValuePair in serializedDrop.toCharacterDrops(ZNetScene.s_instance, this.Prefab))`

**Comment by The-Bees-Decree-Server** [comment]
> I have resolved this issue by changing Line #10 of the AssignDropToCreature Method within the ItemManager.Item Class to resolve the newly changed ZNetScene Instance which is now named s_instance instead of m_instance. here is the changed Line ` foreach (KeyValuePair<Character, CharacterDrop.Drop> keyValuePair in serializedDrop.toCharacterDrops(ZNetScene.s_instance, this.Prefab))`

Thanks for taking the time and doing this although ours were being worked on, also there was a change in m_players as well. We ask you remove your uploads. Thank you.
